#服务的名称
spring:
  application:
    name: micr-web
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    servlet:
      load-on-startup: 1
  redis:
    host: localhost
    port: 6379

#端口号
server:
  port: 8000
  servlet:
    context-path: /api
    encoding:
      enabled: true
      charset: UTF-8
      force: true

#配置dubbo,这是dubbo的消费者
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.bjpowernode.front
  consumer:
    check: false
    timeout: 50000
    retries: 0

#关于短信的业务先按照视频中的业务走，使用的是京东万象(jdwx已经停服)
jdwx:
  sms:
    url: https://way.jd.com/chaungxin/dxjk
    appkey: 3680fa919b771148da626bbcbd459475
    content: 【大富科技】你的验证码是 :%s，3分钟内有效，请勿泄露给他人


